site_name: TQuant Lab
site_url: "https://tejtw.github.io/TQuantLab/"
theme:
  name: material
  font: false

  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.instant 
    #- header.autohide  #自动隐藏
    - navigation.instant.progress
    # - navigation.prune #渲染的 HTML 中仅包含可见的导航项
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view
    - content.code.annotate 


  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - media: "(prefers-color-scheme: dark)"
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  
  theme:
  favicon: images/favicon.png

  nav:
    - lecture:
      -Install TQuant Lab: docs\lecture\Install TQuant Lab (3).md
      -Data collection: docs\lecture\Data collection (3).md
      -get_universe 說明: docs\lecture\get_universe說明.md
      -Universe Analysis: docs\lecture\Universe Analysis－using get_universe.md
      -TSMC 買進持有策略: docs\lecture\TSMC buy and hold strategy.md
      -Simple Algorithm: docs\lecture\Simple Algorithm-TargetPercentPipeAlgo.md

copyright: Copyright &copy; TEJ/All Rights Reserved.
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/tejtw
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/showcase/%E5%8F%B0%E7%81%A3%E7%B6%93%E6%BF%9F%E6%96%B0%E5%A0%B1-tej-?originalSubdomain=tw
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-twitter-handle
  version:
    provider: mike
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
